site_name: CMS
site_url: https://cms-dev.github.io/

repo_name: cms-dev/cms
repo_url: https://github.com/cms-dev/cms

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - redirects:
      redirect_maps:
        'screenshots.html': 'screenshots.md'
        'testimonials.html': 'testimonials.md'
        'contribute.html': 'contribute.md'
        'related.html': 'related.md'

nav:
  - index.md
  - screenshots.md
  - testimonials.md
  - contribute.md
  - related.md
  - contact.md
